# Generated by Django 4.2.7 on 2023-12-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
